name: Release

on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: 'Release branch name (e.g., release/v0.36.5)'
        required: true
        type: string
      version:
        description: 'Release version (e.g., 0.36.5)'
        required: true
        type: string
      publish_release:
        description: 'Publish the release (if false, creates draft)'
        required: false
        type: boolean
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_WRITE_TOKEN || secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.event.inputs.release_branch }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Bump version
        run: |
          python scripts/bump_geemap_version.py ${{ github.event.inputs.version }}
      
      - name: Commit and push changes
        run: |
          git add pyproject.toml geemap/__init__.py
          git commit -m "Bump version to ${{ github.event.inputs.version }}"
          git push origin ${{ github.event.inputs.release_branch }}
      
      - name: Create and push tag
        run: |
          VERSION="${{ github.event.inputs.version }}"
          TAG="v${VERSION}"
          git tag -a "${TAG}" -m "Release ${VERSION}"
          git push origin "${TAG}"
      
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_WRITE_TOKEN || secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: |
            Release ${{ github.event.inputs.version }}
            
            See the [CHANGELOG](https://github.com/jdbcode/geemap/blob/master/CHANGELOG.md) for details.
          draft: ${{ !github.event.inputs.publish_release }}
          prerelease: false
